- hosts: LinuxServer
  gather_facts: true
  become: true
  roles:
  - { role: docker, tags: [ 'docker']}

- hosts: routers 
  gather_facts: true
  become: true
  roles:
  - { role: routers, tags: [ 'routers']}

- hosts: switches
  gather_facts: true
  become: true
  roles:
  - { role: switches, tags: [ 'switches']}

- hosts: WindowsServer
  gather_facts: true
  become: yes
  become_method: runas
  become_user: Administrator
  roles:
  - { role: windows, tags: [ 'windows']}
