- hosts: LinuxServer
  gather_facts: true
  become: true
  roles:
  - { role: docker, tags: [ 'docker']}
<<<<<<< HEAD
  - { role: linux, tags: [ 'linux']}
  - { role: ntp, tags: [ 'ntp']}
  - { role: Linux backup, tags: [ 'sync']}
  - { role: Linux SSH, tags: [ 'ssh']}
  - { role: Sebastiaan Linux, tags: [ 'sebas']}
=======
  - { role: ntp, tags: [ 'ntp']}
>>>>>>> 22f0839c956398797d66d65d211ab7d0697c8ef7

- hosts: routers 
  gather_facts: true
  become: true
  roles:
  - { role: routers, tags: [ 'routers']}

- hosts: switches
  gather_facts: true
  become: true
  roles:
  - { role: switches, tags: [ 'switches']}

- hosts: WindowsServer
  gather_facts: true
  become: yes
  become_method: runas
  become_user: Administrator
  roles:
<<<<<<< HEAD
  - { role: windows, tags: [ 'windows']} 
  - { role: Windows Updates, tags: [ 'update']}

- hosts: Workstations
=======
  - { role: windows, tags: [ 'windows']}
  - { role: windows updates, tags: [ 'updates']}

- hosts: Werkstations
>>>>>>> 22f0839c956398797d66d65d211ab7d0697c8ef7
  gather_facts: true
  become: yes
  become_method: runas
  become_user: Administrator
  roles:
<<<<<<< HEAD
  - { role: workstation, tags: [ 'workstation']}
=======
  - { role: werkstations, tags: [ 'werkstations']}
>>>>>>> 22f0839c956398797d66d65d211ab7d0697c8ef7
