- name: "Update + Upgrade"
  apt:
    force_apt_get: true
    upgrade: dist
    update_cache: true
    cache_valid_time: 3600

- name: Install required system packages
  apt:
    name: "{{ sys_packages }}"
    state: latest
