- name: Ensure group docker exists
  group:
    name: docker
    state: present

- name: Ensure ansible_user is in docker AND sudo group
  user:
    name: "{{ ansible_user }}"
    groups: docker,sudo
    append: yes
  
- name: Update + upgrade the system
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - docker.io
    - docker-compose
    - python3-pip

- name: Ensure docker is enabled + started
  service:
    name: docker
    enabled: yes
    state: started

- name: "Kijk of de volgende directories bestaan"
  stat:
    path: "{{ item }}"
  register: dir_check
  loop:
    - ./nextcloud/data
    - ./nextcloud/db

- name: "Maak de directory's aan als ze niet bestaan"
  file:
    path: "{{ item.item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: docker
    mode: '0775'
  loop: "{{ dir_check.results }}"
  when: not item.stat.exists

- name: "Kopieer de docker-compose.yml naar de server"
  copy:
    src: ./docker-compose.yml
    dest: /home/{{ ansible_user }}/docker-compose.yml
    owner: "{{ ansible_user }}"
    group: "docker"
    mode: 0644

- name: "Check of de containers al draaien"
  shell: docker ps -q -a --filter "status=running"
  register: running_containers
  failed_when: false

- name: "Start de containers als ze nog niet draaien"
  docker_compose:
    project_src: /home/{{ ansible_user }}/
    state: present
  when: running_containers.stdout_lines | length == 0