---
ansible_host: x.x.x.x
sys_packages:
  - apt-transport-https
  - curl
  - software-properties-common
  - build-essential
  - vim
  - git

# sshGuard
sshguard_default_whitelist:
  - "127.0.0.0/8"
  - "::1/128"

sshguard_version: 2.4.3
homefolder: /home/{{ansible_user}}
__sshguard_config_file: /usr/local/etc/sshguard.conf
threshold: 20
ipv4_subnet: 31
sshguard_manage_config: true

# NTP
__ntp_daemon: ntp
ntp_tzdata_package: tzdata
__ntp_package: ntp
__ntp_config_file: /etc/ntp.conf
__ntp_driftfile: /var/lib/ntp/drift
ntp_cron_daemon: cron

ntp_enabled: true
ntp_timezone: Etc/UTC

ntp_manage_config: true

# See: http://support.ntp.org/bin/view/Servers/NTPPoolServers
ntp_area: 'nl'
ntp_servers:
  - "0{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
  - "1{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
  - "2{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
  - "3{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"

ntp_restrict:
  - "127.0.0.1"
  - "::1"

ntp_cron_handler_enabled: false
ntp_tinker_panic: true

# SSH
ssh_ansible_managed: true

AllowedUsers:
  - maid@192.168.112.*

Port: 22
MaxAuthTries: 5
__ssh_config_file: /etc/ssh/sshd_config